name: ChatGames
version: ${project.version}
author: Mas281

depend: [ActionUtil, PlaceholderAPI]
main: io.samdev.chatgames.ChatGames
api-version: 1.14

commands:
  chatgames:
    aliases: [cg]